# Generated by Django 5.1.1 on 2024-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
